import {notFound} from 'next/navigation';
import type {Metadata} from 'next';
import {SlidersHorizontal} from 'lucide-react';
import {SiteHeader} from '@/components/site-header';
import {ProductCard} from '@/components/product-card';
import {categories,products} from '@/lib/catalog';
const base='https://eventequipmentdirect.com';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const c=categories.find(x=>x.slug===slug);if(!c)return{};const title=`Commercial ${c.name} for Sale`;const description=`Shop ${c.kicker.toLowerCase()} for rental companies, venues and event professionals. Compare commercial equipment, specifications and nationwide fulfillment.`;return{title,description,alternates:{canonical:`/category/${c.slug}`},openGraph:{title:`${title} | Event Equipment Direct`,description,url:`${base}/category/${c.slug}`,images:[{url:c.image,alt:`Commercial ${c.name}`}]}}}
export default async function CategoryPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const category=categories.find(c=>c.slug===slug);if(!category)notFound();const items=products.filter(p=>p.category===category.slug);const schema={"@context":"https://schema.org","@type":"CollectionPage",name:`Commercial ${category.name} for Sale`,url:`${base}/category/${category.slug}`,mainEntity:{"@type":"ItemList",itemListElement:items.map((p,i)=>({"@type":"ListItem",position:i+1,url:`${base}/product/${p.slug}`,name:p.name}))}};return <main><SiteHeader/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="relative min-h-[330px] overflow-hidden bg-navy"><img src={category.image} alt={`${category.name} commercial event equipment`} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#071827]/95 via-[#071827]/70 to-transparent"/><div className="container-shell relative flex min-h-[330px] flex-col justify-center text-white"><div className="text-sm font-bold uppercase tracking-widest text-orange">Commercial equipment</div><h1 className="mt-2 text-5xl font-black">Commercial {category.name} for Sale</h1><p className="mt-3 max-w-2xl text-slate-200">{category.kicker}. Compare business-focused equipment, specifications, fulfillment details and compatible accessories.</p></div></section><div className="container-shell grid gap-8 py-10 lg:grid-cols-[240px_1fr]"><aside className="hidden lg:block"><div className="mb-5 flex items-center gap-2 font-black"><SlidersHorizontal className="h-5 w-5"/>Filters</div>{['Equipment type','Size / capacity','Commercial use','Availability','Shipping method','Price'].map(x=><div className="border-t py-4 text-sm font-bold" key={x}>{x}</div>)}</aside><section><div className="mb-6 flex items-center justify-between"><span className="text-sm text-slate-500">{items.length} catalog item{items.length===1?'':'s'}</span><select className="rounded-lg border px-4 py-2 text-sm"><option>Recommended</option><option>Price: Low to High</option><option>Price: High to Low</option></select></div>{items.length?<div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{items.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="overflow-hidden rounded-2xl border bg-white"><img src={category.image} alt={`${category.name} equipment`} className="h-64 w-full object-cover"/><div className="p-8 text-center"><h2 className="text-xl font-black">More commercial {category.name.toLowerCase()} are being verified</h2><p className="mt-2 text-slate-500">Request a quote for equipment not yet listed online.</p></div></div>}</section></div></main>}
