import Link from "next/link";
import { ArrowRight, Check, PackageCheck, ShieldCheck, Truck, Wrench } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { ProductCard } from "@/components/product-card";
import { categories, products } from "@/lib/catalog";

export default function Home(){return <main><SiteHeader/>
<section className="overflow-hidden bg-sand"><div className="container-shell grid min-h-[560px] items-center gap-10 py-14 lg:grid-cols-[1.05fr_.95fr] lg:py-20"><div><div className="mb-5 inline-flex rounded-full border border-orange/30 bg-orange/10 px-4 py-2 text-xs font-extrabold uppercase tracking-wider text-orange">Built for event professionals</div><h1 className="max-w-3xl text-4xl font-black leading-[1.05] tracking-tight text-navy sm:text-6xl">Commercial event equipment that works as hard as your rental business.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Shop tents, tables, chairs, inflatables, replacement parts and business-ready equipment packages from one professional supply platform.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/category/tents" className="inline-flex items-center justify-center gap-2 rounded-lg bg-orange px-6 py-4 font-extrabold text-white">Shop Equipment <ArrowRight className="h-5 w-5"/></Link><Link href="/starter-packages" className="inline-flex items-center justify-center rounded-lg border-2 border-navy px-6 py-4 font-extrabold text-navy">Build a Starter Package</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-slate-600">{["Commercial-focused catalog","Nationwide fulfillment","Replacement parts","Bulk quote support"].map(x=><span className="flex items-center gap-2" key={x}><Check className="h-4 w-4 text-orange"/>{x}</span>)}</div></div>
<div className="relative"><div className="rounded-3xl bg-navy p-5 shadow-2xl sm:p-8"><div className="mb-4 text-xs font-bold uppercase tracking-[.25em] text-orange">Equipment headquarters</div><div className="grid grid-cols-2 gap-3">{["20 × 40 TENTS","COMMERCIAL CHAIRS","BANQUET TABLES","INFLATABLES"].map((x,i)=><div key={x} className={`flex aspect-square items-end rounded-2xl p-4 font-black ${i===0?"col-span-2 aspect-[2/1] bg-white text-2xl text-navy":"bg-slate-800 text-white"}`}><span>{x}</span></div>)}</div></div></div></div></section>
<section className="border-y bg-white"><div className="container-shell grid grid-cols-2 divide-x py-6 md:grid-cols-4">{[[Truck,"Nationwide","Shipping options"],[ShieldCheck,"Commercial","Equipment focus"],[Wrench,"Parts","Replacement support"],[PackageCheck,"Bulk","Business ordering"]].map(([Icon,a,b]:any)=><div className="flex items-center justify-center gap-3 px-3" key={a}><Icon className="h-6 w-6 text-orange"/><div><b>{a}</b><div className="text-xs text-slate-500">{b}</div></div></div>)}</div></section>
<section className="container-shell py-16"><div className="mb-8 flex items-end justify-between"><div><div className="text-sm font-extrabold uppercase tracking-widest text-orange">Shop equipment</div><h2 className="mt-2 text-3xl font-black tracking-tight text-navy">Built around how rental companies buy</h2></div></div><div className="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6">{categories.map(c=><Link href={`/category/${c.slug}`} key={c.slug} className="rounded-xl border bg-white p-5 transition hover:border-orange hover:shadow-soft"><div className="text-3xl">{c.icon}</div><div className="mt-8 font-black">{c.name}</div><div className="mt-1 text-xs leading-5 text-slate-500">{c.kicker}</div></Link>)}</div></section>
<section className="bg-slate-50 py-16"><div className="container-shell"><div className="mb-8"><div className="text-sm font-extrabold uppercase tracking-widest text-orange">Featured equipment</div><h2 className="mt-2 text-3xl font-black text-navy">Start with proven rental categories</h2><p className="mt-3 max-w-2xl text-slate-600">Catalog data is structured for supplier verification before products are published or promised as available.</p></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
<section className="container-shell py-16"><div className="rounded-3xl bg-navy px-6 py-12 text-white sm:px-12"><div className="max-w-3xl"><div className="text-sm font-bold uppercase tracking-widest text-orange">Starting or expanding?</div><h2 className="mt-3 text-3xl font-black sm:text-4xl">Build an inventory instead of guessing what to buy.</h2><p className="mt-4 leading-7 text-slate-300">Starter packages will combine compatible tents, seating, tables, installation equipment and accessories into editable business-ready bundles.</p><Link href="/starter-packages" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-white px-5 py-3 font-extrabold text-navy">Explore Starter Packages <ArrowRight className="h-4 w-4"/></Link></div></div></section>
<footer className="border-t bg-slate-950 py-12 text-slate-300"><div className="container-shell"><div className="text-xl font-black text-white">FRIENDLY <span className="text-orange">SUPPLY</span></div><p className="mt-3 max-w-xl text-sm leading-6">Commercial event equipment platform. Product availability, specifications, freight and warranty data must be verified with connected suppliers before fulfillment.</p></div></footer>
</main>}
