import Link from 'next/link';

const categoryData=[
 {name:'Pole Tents',sub:'Classic commercial tent systems',img:'https://image.made-in-china.com/202f0j00cKJMAsIddPbe/Hot-Sale-Big-Nigeria-Wedding-Party-Tent-for-Sale.jpg'},
 {name:'Frame Tents',sub:'Open interiors with no center poles',img:'https://images.squarespace-cdn.com/content/v1/69af2354d99dde13640f725b/b0ef3456-6ec3-4d7e-86a7-e1801064aa2d/Event_Tent.jpeg'},
 {name:'Tables & Chairs',sub:'Commercial seating and banquet equipment',img:'https://specialeventsales.com/cdn/shop/files/SESWebsitePhotos_17.png?v=1764184983'},
 {name:'Inflatables',sub:'Bounce houses, slides and interactives',img:'https://www.bouncewaveslidesales.com/cdn/shop/files/carnival-xl-commercial-grade-bounce-house-714793.webp?v=1725958390&width=1946'},
 {name:'Tent Parts',sub:'Stakes, ratchets, poles and fittings',img:'https://www.vispronet.de/media/catalog/product/p/a/partyzelte-sturmsicherung-lieferumfang_3.jpg'},
 {name:'Linens & Event Gear',sub:'Finishing pieces for event inventories',img:'https://cdn11.bigcommerce.com/s-jqwssthhhd/images/stencil/1280x1280/products/185/924/70x144-white-linen-tablecloth-for-sale1__91518.1591194998.jpg?c=1'}
];
const tentSizes=['10 × 10','10 × 20','20 × 20','20 × 30','20 × 40','20 × 60','30 × 30','30 × 45','30 × 60','40 × 40','40 × 60','40 × 80'];
const products=[
 {name:'20 × 20 Commercial Pole Tent',type:'Complete Tent System',price:'Supplier pricing pending',img:categoryData[0].img},
 {name:'20 × 40 Commercial Frame Tent',type:'Commercial Frame Tent',price:'Request a quote',img:categoryData[1].img},
 {name:'White Resin Folding Chair',type:'Commercial Event Seating',price:'Bulk pricing pending',img:categoryData[2].img},
 {name:'8 ft Commercial Banquet Table',type:'Rental Fleet Table',price:'Volume pricing pending',img:'https://i5.walmartimages.com/asr/6193c068-5607-4486-88c6-05276d46a233.9e525a80e1bf670edb3c045df4aa5395.jpeg?odnBg=FFFFFF&odnHeight=768&odnWidth=768'},
 {name:'Commercial Bounce House',type:'Rental-Grade Inflatable',price:'Request a quote',img:categoryData[3].img}
];
export default function Home(){return <main>
<div className="supplierBar"><span>Commercial event equipment for rental companies</span><span>Bulk Orders & Fleet Quotes</span><span>Parts & Replacement Support</span></div>
<header className="storeHeader"><Link href="/" className="logo"><b>FRIENDLY</b><span>SUPPLY</span></Link><div className="bigSearch"><span>⌕</span><input aria-label="Search equipment" placeholder="Search tents, chairs, tables, parts, inflatables..."/><button>Search</button></div><div className="headerLinks"><a href="#help"><b>Need help?</b><small>Buying support</small></a><Link href="/admin"><b>Account</b><small>Dealer portal</small></Link><a href="#quote" className="cart">Quote List</a></div></header>
<nav className="megaNav"><a href="#tents">Tents ▾</a><a href="#shop">Tables & Chairs</a><a href="#shop">Inflatables</a><a href="#parts">Tent Parts</a><a href="#shop">Event Accessories</a><Link href="/starter-packages">Starter Packages</Link><a className="navDeal" href="#quote">Bulk / Dealer Quotes</a></nav>
<section className="commerceHero"><div className="commerceHeroImage" style={{backgroundImage:`linear-gradient(90deg,rgba(7,19,31,.78),rgba(7,19,31,.2)),url('${categoryData[0].img}')`}}><div className="commerceHeroCopy"><p className="eyebrow">COMMERCIAL EQUIPMENT • BUILT FOR REPEATED USE</p><h1>Equipment for the companies that make events happen.</h1><p>Shop commercial tents, tables, chairs, inflatables, replacement parts and fleet essentials. Built around the way rental operators actually buy.</p><div><a className="primary" href="#shop">Shop Equipment</a><a className="heroOutline" href="#quote">Request Bulk Quote</a></div></div></div></section>
<section className="quickBenefits"><div><b>Commercial-focused</b><span>Equipment for professional use</span></div><div><b>Parts matter</b><span>Repair and maintain your fleet</span></div><div><b>Large orders welcome</b><span>Package and volume quotes</span></div><div><b>Real buying guidance</b><span>Specs before marketing fluff</span></div></section>
<section id="shop" className="shopSection"><div className="shopTitle"><div><p className="eyebrow">SHOP EQUIPMENT</p><h2>Start with a category.</h2></div><span>Commercial catalog being built from verified supplier relationships.</span></div><div className="supplierCategories">{categoryData.map(c=><a className="supplierCategory" key={c.name} href="#products"><div className="supplierCatImg" style={{backgroundImage:`url('${c.img}')`}}></div><div><h3>{c.name}</h3><p>{c.sub}</p><b>Shop now →</b></div></a>)}</div></section>
<section id="tents" className="tentFinder"><div className="tentFinderIntro"><p className="eyebrow">TENT SIZE FINDER</p><h2>Shop commercial tents by size.</h2><p>Rental operators often know the footprint they need. Start there, then compare pole, frame and high-peak systems.</p></div><div className="sizeGrid">{tentSizes.map(s=><a key={s} href="#products"><b>{s}</b><span>Shop tents →</span></a>)}</div></section>
<section id="products" className="catalogSection"><div className="catalogHeader"><div><p className="eyebrow">COMMERCIAL FAVORITES</p><h2>Equipment rental companies buy every day.</h2></div><a href="#quote">Need volume pricing? Get a quote →</a></div><div className="commerceProducts">{products.map(p=><article key={p.name} className="commerceProduct"><div className="commerceProductImg" style={{backgroundImage:`url('${p.img}')`}}><span>COMMERCIAL</span></div><div className="commerceProductBody"><small>{p.type}</small><h3>{p.name}</h3><p className="availability">● Availability must be verified</p><b className="price">{p.price}</b><div className="productActions"><button>View Details</button><button className="quoteButton">Add to Quote</button></div></div></article>)}</div></section>
<section id="parts" className="partsSection"><div className="partsPhoto" style={{backgroundImage:`url('${categoryData[4].img}')`}}></div><div className="partsCopy"><p className="eyebrow">KEEP YOUR INVENTORY WORKING</p><h2>Replacement parts should be easy to find.</h2><p>A rental supplier is more useful when you can come back for poles, stakes, ratchets, fittings, tops and repair components—not just complete tents.</p><div className="partsLinks"><a href="#quote">Tent Stakes</a><a href="#quote">Ratchets & Straps</a><a href="#quote">Replacement Poles</a><a href="#quote">Frame Components</a><a href="#quote">Tent Tops</a><a href="#quote">Sidewalls</a></div></div></section>
<section className="businessBuilder"><div><p className="eyebrow">NEW RENTAL BUSINESS?</p><h2>Build an inventory, not a random shopping cart.</h2><p>Start with guest capacity and event type. Our package builder is designed to group compatible tents, tables, chairs, anchoring and supporting equipment.</p><Link className="primary" href="/starter-packages">Explore Starter Packages</Link></div><div className="builderChecklist"><b>Starter inventory planning</b><span>✓ Tent systems</span><span>✓ Tables and seating</span><span>✓ Anchoring & installation tools</span><span>✓ Replacement essentials</span><span>✓ Storage & transport accessories</span></div></section>
<section id="quote" className="quoteSection"><div><p className="eyebrow">BUYING MULTIPLE UNITS?</p><h2>Get a commercial equipment quote.</h2><p>Tell us what you're building and what quantities you need. Large orders should be reviewed for supplier availability, freight and volume pricing before purchase.</p></div><form className="quoteMock"><input placeholder="Business name"/><input placeholder="Email"/><input placeholder="Phone"/><textarea placeholder="What equipment and quantities do you need?"></textarea><button type="button">Start Quote Request</button></form></section>
<section id="help" className="supportStrip"><b>Need help choosing equipment?</b><span>Use the quote request for sizing, fleet planning, parts compatibility and bulk purchasing.</span><a href="#quote">Talk to Buying Support →</a></section>
<footer className="storeFooter"><div><div className="logo"><b>FRIENDLY</b><span>SUPPLY</span></div><p>Commercial event equipment for rental operators, venues and event professionals.</p></div><div><b>Shop</b><a href="#tents">Commercial Tents</a><a href="#shop">Tables & Chairs</a><a href="#shop">Inflatables</a><a href="#parts">Parts & Accessories</a></div><div><b>Business</b><Link href="/starter-packages">Starter Packages</Link><a href="#quote">Bulk Quotes</a><Link href="/admin">Dealer Portal</Link></div><div><b>Important</b><span>Product specs, inventory, lead times and pricing are published only after supplier verification.</span></div></footer>
</main>}
