import Link from 'next/link';
import { SiteHeader } from '@/components/site-header';
import { categories, products, money } from '@/lib/catalog';

const hero='https://images.pexels.com/photos/8392460/pexels-photo-8392460.jpeg?auto=compress&cs=tinysrgb&w=1800';
const visualCats=categories.map(c=>[c.slug,c.name,c.kicker,c.image]);
const sizes=['20 × 20','20 × 30','20 × 40','30 × 30','30 × 45','30 × 60','40 × 40','40 × 60','40 × 80'];

export default function Home(){const featured=products.slice(0,4);return <main className="newHome"><SiteHeader/>
<section className="newHero" style={{backgroundImage:`linear-gradient(90deg,rgba(6,17,30,.96) 0%,rgba(6,17,30,.82) 43%,rgba(6,17,30,.18) 72%),url('${hero}')`}}><div className="newHeroInner"><div className="heroBadge">COMMERCIAL EVENT EQUIPMENT • SHIPPED NATIONWIDE</div><h1>Equipment built to<br/><em>earn event after event.</em></h1><p>Commercial tents, tables, chairs, inflatables and replacement parts for rental companies, venues and event professionals.</p><div className="newHeroActions"><a href="#departments" className="newPrimary">Shop Equipment</a><Link href="/quote" className="newSecondary">Request Bulk Quote</Link></div><div className="trustRow"><span>✓ Commercial-grade focus</span><span>✓ Freight reviewed before fulfillment</span><span>✓ Replacement-part support</span></div></div></section>
<section className="quickBuy"><b>WHAT ARE YOU BUYING?</b><a href="#tents">A complete tent</a><a href="#sizes">A specific tent size</a><a href="#departments">Tables & chairs</a><a href="#parts">Replacement parts</a><Link href="/starter-packages">A starter rental fleet</Link></section>
<section id="departments" className="newSection"><div className="sectionLead"><div><span>SHOP BY DEPARTMENT</span><h2>Everything your rental fleet needs.</h2></div><p>Built around commercial equipment—not party-store clutter.</p></div><div className="visualDepartments">{visualCats.map(([slug,name,sub,img])=><Link href={`/category/${slug}`} className="visualDepartment" key={name}><div className="visualDepartmentImg" style={{backgroundImage:`linear-gradient(0deg,rgba(7,20,34,.72),rgba(7,20,34,.04) 65%),url('${img}')`}}><div><h3>{name}</h3><p>{sub}</p><b>SHOP NOW →</b></div></div></Link>)}</div></section>
<section id="tents" className="operatorFeature"><div className="operatorPhoto" style={{backgroundImage:`url('${hero}')`}}><div className="photoLabel">COMMERCIAL TENT SYSTEMS</div></div><div className="operatorCopy"><span>BUY LIKE AN OPERATOR</span><h2>Start with the structure. Then build the system.</h2><p>A rental tent is more than vinyl. Compare structure type, footprint, anchoring, included hardware, expansion options and replacement-part availability before you buy.</p><div className="systemRows"><Link href="/category/tents"><b>POLE TENTS</b><small>Fleet workhorses • efficient setup • staked installations</small><strong>→</strong></Link><Link href="/category/tents"><b>FRAME TENTS</b><small>Open interiors • flexible placement • modular components</small><strong>→</strong></Link><Link href="/category/tents"><b>HIGH PEAK SYSTEMS</b><small>Premium presentation • commercial modular designs</small><strong>→</strong></Link></div></div></section>
<section id="sizes" className="sizeShop"><div><span>KNOW YOUR FOOTPRINT?</span><h2>Shop commercial tents by size.</h2><p>Go straight to the dimensions rental customers request most.</p></div><div className="newSizeGrid">{sizes.map(s=><Link href="/category/tents" key={s}><b>{s}</b><small>SHOP SYSTEMS →</small></Link>)}</div></section>
<section className="featuredProducts"><div className="sectionLead light"><div><span>FLEET WORKHORSES</span><h2>Equipment worth comparing first.</h2></div><Link href="/quote">Buying in quantity? Get a commercial quote →</Link></div><div className="featuredGrid">{featured.map(p=><Link href={`/product/${p.slug}`} className="featuredCard" key={p.slug}><div className="featuredImage" style={{padding:0,overflow:'hidden'}}><img src={p.image} alt={p.imageAlt} loading="lazy" style={{width:'100%',height:'100%',objectFit:'cover'}}/><span>COMMERCIAL</span></div><div className="featuredBody"><small>{p.category.replaceAll('-',' ')}</small><h3>{p.name}</h3><p>{p.summary}</p><div className="featuredBottom"><b>{money(p.price)}</b><strong>VIEW →</strong></div></div></Link>)}</div></section>
<section id="parts" className="partsCallout"><div><span>PARTS & REPAIR</span><h2>Downtime costs more than the part.</h2><p>Build a dependable shelf of stakes, ratchets, fittings, replacement tops, sidewalls, blowers and repair supplies before the busy weekend.</p><Link href="/quote" className="newPrimary">Find a Replacement Part</Link></div><div className="partsStats"><div><b>01</b><strong>Identify the equipment</strong><p>Brand, system, size and component.</p></div><div><b>02</b><strong>Verify compatibility</strong><p>No guessing with commercial hardware.</p></div><div><b>03</b><strong>Get it back in service</strong><p>Protect revenue-producing inventory.</p></div></div></section>
<section className="businessCTA"><span>STARTING OR EXPANDING A RENTAL COMPANY?</span><h2>Build a fleet around the jobs you want to book.</h2><p>Plan tents, tables, chairs, anchoring, transport, spares and repair gear as one system instead of buying random equipment.</p><div><Link href="/starter-packages" className="newPrimary">Build a Starter Fleet</Link><Link href="/quote" className="darkOutline">Talk Through My Order</Link></div></section>
</main>}
