export type Category={name:string;slug:string;kicker:string;icon:string;image:string};
export type Product={id:string;name:string;slug:string;category:string;price:number;compareAt?:number;badge?:string;summary:string;availability:"In stock"|"Low stock"|"Confirm availability";specs:Record<string,string>;included:string[];imageLabel:string;image:string;imageAlt:string;supplier:string;supplierUrl:string};

const tentImage="https://images.pexels.com/photos/8392460/pexels-photo-8392460.jpeg?auto=compress&cs=tinysrgb&w=1400";
const chairImage="https://images.pexels.com/photos/29188023/pexels-photo-29188023.jpeg?auto=compress&cs=tinysrgb&w=1200";
const tableImage="https://images.pexels.com/photos/2788487/pexels-photo-2788487.jpeg?auto=compress&cs=tinysrgb&w=1200";
const inflatableImage="https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=1200";
const partsImage="https://images.pexels.com/photos/162553/keys-workshop-mechanic-tools-162553.jpeg?auto=compress&cs=tinysrgb&w=1200";
const accessoryImage="https://images.pexels.com/photos/2263436/pexels-photo-2263436.jpeg?auto=compress&cs=tinysrgb&w=1200";

export const categories:Category[]=[
{name:"Tents",slug:"tents",kicker:"Pole, frame & high peak",icon:"⛺",image:tentImage},{name:"Chairs",slug:"chairs",kicker:"Folding, resin & event",icon:"▥",image:chairImage},{name:"Tables",slug:"tables",kicker:"Banquet, round & cocktail",icon:"▰",image:tableImage},{name:"Inflatables",slug:"inflatables",kicker:"Bounce, slides & obstacles",icon:"◒",image:inflatableImage},{name:"Tent Parts",slug:"tent-parts",kicker:"Poles, stakes & replacements",icon:"⌁",image:partsImage},{name:"Accessories",slug:"accessories",kicker:"Blowers, anchoring & repair",icon:"✦",image:accessoryImage}];

export const products:Product[]=[
{id:"p1",name:"20' × 20' Premium High Peak Frame Party Tent",slug:"20x20-premium-high-peak-frame-tent",category:"tents",price:1999.99,badge:"Commercial",summary:"Commercial high-peak frame tent currently listed by Tent & Table for event and rental use.",availability:"Confirm availability",imageLabel:"20 × 20 HIGH PEAK FRAME TENT",image:tentImage,imageAlt:"White commercial event tent with tables and chairs",supplier:"Tent & Table",supplierUrl:"https://www.tentandtable.net/",specs:{"Tent style":"High peak frame","Footprint":"20 × 20 ft","Use":"Commercial event equipment","Supplier":"Tent & Table","Fulfillment":"Verify before order"},included:["Complete configuration per supplier listing — verify current contents before fulfillment"]},
{id:"p2",name:"Oxford White Resin Chair — 56 Pack",slug:"oxford-white-resin-chair-56-pack",category:"chairs",price:1519.84,badge:"Rental Fleet Pack",summary:"Bulk commercial white resin folding-chair package currently listed by CELINA/GetTent.",availability:"Confirm availability",imageLabel:"OXFORD WHITE RESIN • 56 PACK",image:chairImage,imageAlt:"White event chairs arranged outdoors",supplier:"CELINA / GetTent",supplierUrl:"https://gettent.com/",specs:{"Style":"Resin folding chair","Color":"White","Pack":"56 chairs","Supplier":"CELINA / GetTent","Fulfillment":"Verify before order"},included:["56 Oxford white resin chairs"]},
{id:"p3",name:"8' × 30\" Wood Banquet Table",slug:"8ft-wood-banquet-table",category:"tables",price:139.31,badge:"Commercial",summary:"Eight-foot commercial wood banquet table currently listed by CELINA/GetTent.",availability:"Confirm availability",imageLabel:"8 FT WOOD BANQUET TABLE",image:tableImage,imageAlt:"Event tables and chairs prepared for a reception",supplier:"CELINA / GetTent",supplierUrl:"https://gettent.com/",specs:{"Length":"8 ft","Width":"30 in","Style":"Wood banquet table","Supplier":"CELINA / GetTent","Fulfillment":"Verify before order"},included:["1 banquet table"]},
{id:"p4",name:"18' Blue Marble Inflatable Water Slide with Blower",slug:"18ft-blue-marble-water-slide",category:"inflatables",price:2899,badge:"Commercial Inflatable",summary:"Commercial 18-foot water slide currently listed by Tent & Table with blower.",availability:"Confirm availability",imageLabel:"18 FT BLUE MARBLE WATER SLIDE",image:inflatableImage,imageAlt:"Colorful outdoor recreation equipment representing commercial inflatables",supplier:"Tent & Table",supplierUrl:"https://www.tentandtable.net/",specs:{"Type":"Water slide","Height":"18 ft class","Use":"Commercial rental","Blower":"Included per current supplier listing","Fulfillment":"Verify before order"},included:["Inflatable water slide","Blower per supplier listing"]},
{id:"p5",name:"20' × 20' Premium Canopy Pole Party Tent",slug:"20x20-premium-canopy-pole-tent",category:"tents",price:1299.99,badge:"Commercial",summary:"Commercial pole-party-tent system currently listed by Tent & Table.",availability:"Confirm availability",imageLabel:"20 × 20 CANOPY POLE TENT",image:tentImage,imageAlt:"White outdoor event tent on grass",supplier:"Tent & Table",supplierUrl:"https://www.tentandtable.net/",specs:{"Tent style":"Pole tent","Footprint":"20 × 20 ft","Supplier":"Tent & Table","Fulfillment":"Verify before order"},included:["Verify complete current kit contents with supplier"]},
{id:"p6",name:"60\" Round Laminate Table",slug:"60in-round-laminate-table",category:"tables",price:222.44,summary:"Commercial sixty-inch round laminate event table listed in CELINA's distributor/reseller catalog.",availability:"Confirm availability",imageLabel:"60 IN ROUND LAMINATE TABLE",image:tableImage,imageAlt:"Round event tables arranged for an outdoor reception",supplier:"CELINA / GetTent",supplierUrl:"https://gettent.com/by-industry/distributors-and-resellers/",specs:{"Diameter":"60 in","Top":"Laminate","Supplier":"CELINA / GetTent","Fulfillment":"Verify before order"},included:["1 round table"]},
{id:"p7",name:"Bellbrook White Chair — 120 Pack",slug:"bellbrook-white-chair-120-pack",category:"chairs",price:1737.48,badge:"Bulk Pack",summary:"Large commercial white-chair package listed in CELINA's distributor/reseller catalog.",availability:"Confirm availability",imageLabel:"BELLBROOK WHITE • 120 PACK",image:chairImage,imageAlt:"Rows of white event chairs outdoors",supplier:"CELINA / GetTent",supplierUrl:"https://gettent.com/by-industry/distributors-and-resellers/",specs:{"Color":"White","Pack":"120 chairs","Supplier":"CELINA / GetTent","Fulfillment":"Verify before order"},included:["120 Bellbrook white chairs"]},
{id:"p8",name:"Zoom LTE Commercial Blower Trio",slug:"zoom-lte-commercial-blower-trio",category:"accessories",price:599.97,badge:"Commercial",summary:"1 HP, 1.5 HP and 2 HP commercial inflatable blower trio currently listed by Tent & Table.",availability:"Confirm availability",imageLabel:"COMMERCIAL BLOWER TRIO",image:accessoryImage,imageAlt:"Commercial event equipment in use at an outdoor event",supplier:"Tent & Table",supplierUrl:"https://www.tentandtable.net/",specs:{"Blowers":"1 HP / 1.5 HP / 2 HP","Use":"Commercial inflatables","Supplier":"Tent & Table","Fulfillment":"Verify before order"},included:["1 HP blower","1.5 HP blower","2 HP blower"]}
];
export const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(value);
