import { notFound } from "next/navigation";
import Link from "next/link";
import { Check, ChevronRight, Package, ShieldCheck, Truck } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { money, products } from "@/lib/catalog";

export default function ProductPage({params}:{params:{slug:string}}){const p=products.find(x=>x.slug===params.slug);if(!p)notFound();return <main><SiteHeader/><div className="container-shell py-8"><div className="mb-7 flex items-center gap-2 text-xs text-slate-500"><Link href="/">Home</Link><ChevronRight className="h-3 w-3"/><Link href={`/category/${p.category}`}>{p.category}</Link><ChevronRight className="h-3 w-3"/><span>{p.name}</span></div><div className="grid gap-10 lg:grid-cols-2"><div><div className="flex aspect-square items-center justify-center rounded-2xl bg-gradient-to-br from-slate-100 to-slate-200 text-center text-4xl font-black text-slate-400">{p.imageLabel}</div><div className="mt-3 grid grid-cols-4 gap-3">{[1,2,3,4].map(i=><div className="aspect-square rounded-lg bg-slate-100" key={i}/>)}</div></div><div><div className="text-sm font-bold uppercase tracking-widest text-orange">Commercial equipment</div><h1 className="mt-3 text-4xl font-black leading-tight text-navy">{p.name}</h1><p className="mt-4 text-lg leading-8 text-slate-600">{p.summary}</p><div className="mt-6 text-sm font-bold text-emerald-700">● {p.availability}</div><div className="mt-2 text-4xl font-black">{money(p.price)}</div><div className="text-sm text-slate-500">Freight and final availability calculated/confirmed before fulfillment.</div><div className="mt-7 rounded-xl border bg-slate-50 p-5"><label className="text-xs font-black uppercase tracking-wider">Quantity</label><div className="mt-2 flex gap-3"><input defaultValue="1" type="number" min="1" className="w-24 rounded-lg border bg-white px-4 py-3"/><button className="flex-1 rounded-lg bg-orange px-5 py-3 font-black text-white">Add to Cart</button></div><button className="mt-3 w-full rounded-lg border-2 border-navy px-5 py-3 font-black text-navy">Request Bulk Quote</button></div><div className="mt-6 grid grid-cols-3 gap-3 text-center text-xs font-bold">{[[Truck,"Freight Ready"],[Package,"Parts Support"],[ShieldCheck,"Data Verified"]].map(([Icon,x]:any)=><div className="rounded-lg border p-3" key={x}><Icon className="mx-auto mb-2 h-5 w-5 text-orange"/>{x}</div>)}</div></div></div>
<div className="mt-14 grid gap-8 lg:grid-cols-2"><section><h2 className="text-2xl font-black text-navy">What's included</h2><div className="mt-4 divide-y rounded-xl border">{p.included.map(x=><div className="flex items-center gap-3 p-4" key={x}><Check className="h-5 w-5 text-emerald-600"/>{x}</div>)}</div><p className="mt-3 text-xs leading-5 text-slate-500">Exact included components must be verified against the selected supplier listing before publication and fulfillment.</p></section><section><h2 className="text-2xl font-black text-navy">Specifications</h2><div className="mt-4 overflow-hidden rounded-xl border">{Object.entries(p.specs).map(([k,v])=><div className="grid grid-cols-2 border-b last:border-0" key={k}><div className="bg-slate-50 p-4 text-sm font-bold">{k}</div><div className="p-4 text-sm">{v}</div></div>)}</div></section></div>
<section className="mt-14 rounded-2xl bg-navy p-8 text-white"><h2 className="text-2xl font-black">Buying for a rental company?</h2><p className="mt-3 max-w-2xl leading-7 text-slate-300">Get a business quote for multiple units, compatible accessories, replacement parts and freight instead of piecing together a large order yourself.</p><button className="mt-5 rounded-lg bg-white px-5 py-3 font-black text-navy">Request Commercial Quote</button></section></div></main>}
